name: PR build fake backend images for smoke tests

on:
  pull_request:
    paths:
      - 'smoke-tests/images/fake-backend/**'
      - '.github/workflows/pr-smoke-test-fake-backend-images.yml'

jobs:
  buildLinux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Set up JDK 11 for running Gradle
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Cache gradle dependencies
        uses: burrunan/gradle-cache-action@v1.19
        with:
          job-id: fakebackend-smoke
          read-only: true

      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-cache-${{ hashFiles('smoke-tests/images/fake-backend/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Build Docker Image
        run: ./gradlew jibDockerBuild -Djib.httpTimeout=120000 -Djib.console=plain
        working-directory: smoke-tests/images/fake-backend

  buildWindows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true

      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Set up JDK 11 for running Gradle
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Cache gradle dependencies
        uses: burrunan/gradle-cache-action@v1.19
        with:
          job-id: fakebackend-smoke

      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-cache-${{ hashFiles('smoke-tests/images/fake-backend/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Build Docker Image
        run: ./gradlew windowsBackendImageBuild
        working-directory: smoke-tests/images/fake-backend
